Refactoring test collections folder
project-chip/certification-tool-backend pull request #10
Opened 2023-10-27 18:49 UTC by rquidute

### What changed
This PR is the phase-1 for the feature **Python tests in TH UI**. 
The motivation to refactoring is to prepare the code to retrieve the python tests from SDK. 
The final proposal for the folders organization is described bellow (PS: **python_testing** folder is part of phase 2):

+ test_collections
    + sample_tests
    + python_tests
    + sdk_tests
       + support
          + sdk_runner		
      + sdk_checkout
         + .version
         + yaml_tests
            + models
        + python_testing
           + models
        + __init__.py

### Related Issues
Python tests in TH UI - Phase 1 (Refactoring test_collection folder) - https://github.com/project-chip/certification-tool/issues/72

### Testing

-   Unit test updated and passing
<img width="308" alt="Screenshot 2023-10-27 at 15 47 47" src="https://github.com/project-chip/certification-tool-backend/assets/116586593/bda6ed01-1b76-42d2-98d9-1faccc6794b6">

-   Test case execution successfully in TH  (Automated, Semi-Automated, Simulated, Manual)

2023-10-27 19:14 UTC, mikaelhm requested changes
I think it would be nice to keep a clear separation of content tracked in this repo and content pulled form the SDK repo.

I suggest that we organize it like this:

- `test_collections/sdk_tests/sdk_checkout/` is the only place we put content from SDK, and it only contains content from the SDK
- `test_collections/sdk_tests/support` could contain all the python code we need in our repo, for yaml models etc. But no code from the SDK repo.

This way we can simply delete `sdk_checkout` when we need to update.

2023-10-27 23:18 UTC, mikaelhm approved these changes
Looks good.

But I think we can simplify the excluding of `test_collections/sdk_tests/sdk_checkout`

2023-10-27 23:18 UTC, mikaelhm commented on .flake8
> +exclude = .git,__pycache__,__init__.py,.mypy_cache,.pytest_cache,third_party,test_collections/sdk_tests/sdk_checkout/yaml_tests/yaml/sdk,test_collections/sdk_tests/sdk_checkout/sdk_runner
can we just exclude `test_collections/sdk_tests/sdk_checkout/`

2023-10-27 23:18 UTC, mikaelhm commented on .vscode/settings.json
> +        "test_collections/sdk_tests/sdk_checkout/yaml_tests/yaml/**/*.py"
Again how about just ignoring 
```
test_collections/sdk_tests/sdk_checkout
```

2023-10-27 23:18 UTC, mikaelhm commented on cspell.json
> +        "test_collections/sdk_tests/sdk_checkout/yaml_tests/yaml/sdk",
Again, just ignore `test_collections/sdk_tests/sdk_checkout/`

2023-10-30 17:22 UTC, hiltonlima approved these changes

2023-10-30 18:47 UTC, antonio-amjr approved these changes

2023-10-31 11:24 UTC, merged